[tool.black]
line-length = 120

[tool.isort]
known_first_party = "argoverse"
known_third_party = ""

line_length = 120
multi_line_output = 3
profile = "black"

[tool.mypy]
exclude = "build"
ignore_missing_imports = true
plugins = numpy.typing.mypy_plugin
strict = true
